apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgis.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClassName }}